# Jekyll configuration

name: Javi Rod IT
description: Técnico de Sistemas

# Url is currently only used only for the RSS feed in feed.xml
url: https://javi-rod.github.io/
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: Javier Rodríguez
copyright: 2021-2024

share:
  facebook: true
  twitter: true
  linkedin: true
  email: true

social:
  github: javi-rod
  twitter: javirodti
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: G-DSRMBGY961
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus:
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
